name: Wine WoW64 Manual CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: bootstraps_noble.yml
          workflow_conclusion: success
          path: /opt
      - name: Build Wine using GCC
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf /opt/Bootstraps/bootstraps-noble.tar.xz
          chmod +x build_wine.sh
          USE_LLVM=false ./build_wine.sh
          sha256sum *.tar.xz
      - uses: actions/upload-artifact@v3
        with:
          name: Wine-WoW64-Manual-GCC
          path: ./*.tar.xz
      
      - name : Build Wine using Clang
        run: |
          rm -rf *.tar.xz
          USE_LLVM=true ./build_wine.sh
          sha256sum *.tar.xz

      - uses: actions/upload-artifact@v3
        with:
          name: Wine-WoW64-Manual-Clang
          path: ./*.tar.xz